### ISSUE TITLE
Start?

### ISSUE THREAD

**Issue by peva3** [wnielson/gdvfs#1]
Everything installs fine, but I cant seem to figure out how to actually get this started, sorry if im missing something obvious.

Thanks

**Comment by wnielson** [comment]
Have you run `gdvfs -h`?

**Comment by peva3** [comment]
When trying to use gdvfs -f I get this

gdvfs version 0.3.8, Copyright (C) Weston Nielson wnielson@github

Traceback (most recent call last):
  File "/usr/local/bin/gdvfs", line 9, in <module>
    load_entry_point('gdvfs==0.3.8', 'console_scripts', 'gdvfs')()
  File "build/bdist.linux-x86_64/egg/gdvfs.py", line 725, in main
  File "build/bdist.linux-x86_64/egg/gdvfs.py", line 667, in setup_logging
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'gdvfs'

**Comment by wnielson** [comment]
Sounds like you're missing the config file.  Did you rename `gdvfs.conf.sample` to `gdvfs.conf`?
